//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/Petr/IdeaProjects/SimpleParser/src\Sinumerik.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISinumerikListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class SinumerikBaseListener : ISinumerikListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.parse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParse([NotNull] SinumerikParser.ParseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.parse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParse([NotNull] SinumerikParser.ParseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] SinumerikParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] SinumerikParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] SinumerikParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] SinumerikParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] SinumerikParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] SinumerikParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.vardefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVardefinition([NotNull] SinumerikParser.VardefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.vardefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVardefinition([NotNull] SinumerikParser.VardefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>identifierFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifierFunctionCall([NotNull] SinumerikParser.IdentifierFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>identifierFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifierFunctionCall([NotNull] SinumerikParser.IdentifierFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>printlnFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintlnFunctionCall([NotNull] SinumerikParser.PrintlnFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>printlnFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintlnFunctionCall([NotNull] SinumerikParser.PrintlnFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sinFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSinFunctionCall([NotNull] SinumerikParser.SinFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sinFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSinFunctionCall([NotNull] SinumerikParser.SinFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>cosFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCosFunctionCall([NotNull] SinumerikParser.CosFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>cosFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCosFunctionCall([NotNull] SinumerikParser.CosFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>tanFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTanFunctionCall([NotNull] SinumerikParser.TanFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>tanFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTanFunctionCall([NotNull] SinumerikParser.TanFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>asinFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsinFunctionCall([NotNull] SinumerikParser.AsinFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>asinFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsinFunctionCall([NotNull] SinumerikParser.AsinFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>acosFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAcosFunctionCall([NotNull] SinumerikParser.AcosFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>acosFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAcosFunctionCall([NotNull] SinumerikParser.AcosFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>atanFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtanFunctionCall([NotNull] SinumerikParser.AtanFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>atanFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtanFunctionCall([NotNull] SinumerikParser.AtanFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>atan2FunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtan2FunctionCall([NotNull] SinumerikParser.Atan2FunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>atan2FunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtan2FunctionCall([NotNull] SinumerikParser.Atan2FunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sqrtFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSqrtFunctionCall([NotNull] SinumerikParser.SqrtFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sqrtFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSqrtFunctionCall([NotNull] SinumerikParser.SqrtFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>truncFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTruncFunctionCall([NotNull] SinumerikParser.TruncFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>truncFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTruncFunctionCall([NotNull] SinumerikParser.TruncFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>absFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAbsFunctionCall([NotNull] SinumerikParser.AbsFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>absFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAbsFunctionCall([NotNull] SinumerikParser.AbsFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>potFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPotFunctionCall([NotNull] SinumerikParser.PotFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>potFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPotFunctionCall([NotNull] SinumerikParser.PotFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>roundFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRoundFunctionCall([NotNull] SinumerikParser.RoundFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>roundFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRoundFunctionCall([NotNull] SinumerikParser.RoundFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>modeacFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModeacFunctionCall([NotNull] SinumerikParser.ModeacFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>modeacFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModeacFunctionCall([NotNull] SinumerikParser.ModeacFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>modeicFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModeicFunctionCall([NotNull] SinumerikParser.ModeicFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>modeicFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModeicFunctionCall([NotNull] SinumerikParser.ModeicFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>transFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTransFunctionCall([NotNull] SinumerikParser.TransFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>transFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTransFunctionCall([NotNull] SinumerikParser.TransFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>atransFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtransFunctionCall([NotNull] SinumerikParser.AtransFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>atransFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtransFunctionCall([NotNull] SinumerikParser.AtransFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>rotFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRotFunctionCall([NotNull] SinumerikParser.RotFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>rotFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRotFunctionCall([NotNull] SinumerikParser.RotFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>arotFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArotFunctionCall([NotNull] SinumerikParser.ArotFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>arotFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArotFunctionCall([NotNull] SinumerikParser.ArotFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>scaleFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScaleFunctionCall([NotNull] SinumerikParser.ScaleFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>scaleFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScaleFunctionCall([NotNull] SinumerikParser.ScaleFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ascaleFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAscaleFunctionCall([NotNull] SinumerikParser.AscaleFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ascaleFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAscaleFunctionCall([NotNull] SinumerikParser.AscaleFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>mirrorFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMirrorFunctionCall([NotNull] SinumerikParser.MirrorFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>mirrorFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMirrorFunctionCall([NotNull] SinumerikParser.MirrorFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>amirrorFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAmirrorFunctionCall([NotNull] SinumerikParser.AmirrorFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>amirrorFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAmirrorFunctionCall([NotNull] SinumerikParser.AmirrorFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>oriwksFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOriwksFunctionCall([NotNull] SinumerikParser.OriwksFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>oriwksFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOriwksFunctionCall([NotNull] SinumerikParser.OriwksFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>oriaxesFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOriaxesFunctionCall([NotNull] SinumerikParser.OriaxesFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>oriaxesFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOriaxesFunctionCall([NotNull] SinumerikParser.OriaxesFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>traoriFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTraoriFunctionCall([NotNull] SinumerikParser.TraoriFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>traoriFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTraoriFunctionCall([NotNull] SinumerikParser.TraoriFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>diamonFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDiamonFunctionCall([NotNull] SinumerikParser.DiamonFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>diamonFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDiamonFunctionCall([NotNull] SinumerikParser.DiamonFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>diamofFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDiamofFunctionCall([NotNull] SinumerikParser.DiamofFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>diamofFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDiamofFunctionCall([NotNull] SinumerikParser.DiamofFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>diam90FunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDiam90FunctionCall([NotNull] SinumerikParser.Diam90FunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>diam90FunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDiam90FunctionCall([NotNull] SinumerikParser.Diam90FunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>displofFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDisplofFunctionCall([NotNull] SinumerikParser.DisplofFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>displofFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDisplofFunctionCall([NotNull] SinumerikParser.DisplofFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>displonFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDisplonFunctionCall([NotNull] SinumerikParser.DisplonFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>displonFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDisplonFunctionCall([NotNull] SinumerikParser.DisplonFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sblofFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSblofFunctionCall([NotNull] SinumerikParser.SblofFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sblofFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSblofFunctionCall([NotNull] SinumerikParser.SblofFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>sblonFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSblonFunctionCall([NotNull] SinumerikParser.SblonFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>sblonFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSblonFunctionCall([NotNull] SinumerikParser.SblonFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>xcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterXcoordFunctionCall([NotNull] SinumerikParser.XcoordFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>xcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitXcoordFunctionCall([NotNull] SinumerikParser.XcoordFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ycoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterYcoordFunctionCall([NotNull] SinumerikParser.YcoordFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ycoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitYcoordFunctionCall([NotNull] SinumerikParser.YcoordFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>zcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterZcoordFunctionCall([NotNull] SinumerikParser.ZcoordFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>zcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitZcoordFunctionCall([NotNull] SinumerikParser.ZcoordFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>acoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAcoordFunctionCall([NotNull] SinumerikParser.AcoordFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>acoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAcoordFunctionCall([NotNull] SinumerikParser.AcoordFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>bcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBcoordFunctionCall([NotNull] SinumerikParser.BcoordFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>bcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBcoordFunctionCall([NotNull] SinumerikParser.BcoordFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ccoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCcoordFunctionCall([NotNull] SinumerikParser.CcoordFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ccoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCcoordFunctionCall([NotNull] SinumerikParser.CcoordFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ucoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUcoordFunctionCall([NotNull] SinumerikParser.UcoordFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ucoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUcoordFunctionCall([NotNull] SinumerikParser.UcoordFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>vcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVcoordFunctionCall([NotNull] SinumerikParser.VcoordFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>vcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVcoordFunctionCall([NotNull] SinumerikParser.VcoordFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>wcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWcoordFunctionCall([NotNull] SinumerikParser.WcoordFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>wcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWcoordFunctionCall([NotNull] SinumerikParser.WcoordFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ivectFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIvectFunctionCall([NotNull] SinumerikParser.IvectFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ivectFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIvectFunctionCall([NotNull] SinumerikParser.IvectFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>jvectFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJvectFunctionCall([NotNull] SinumerikParser.JvectFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>jvectFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJvectFunctionCall([NotNull] SinumerikParser.JvectFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>kvectFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKvectFunctionCall([NotNull] SinumerikParser.KvectFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>kvectFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKvectFunctionCall([NotNull] SinumerikParser.KvectFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>radiusFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRadiusFunctionCall([NotNull] SinumerikParser.RadiusFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>radiusFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRadiusFunctionCall([NotNull] SinumerikParser.RadiusFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>turnFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTurnFunctionCall([NotNull] SinumerikParser.TurnFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>turnFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTurnFunctionCall([NotNull] SinumerikParser.TurnFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>mmodeFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMmodeFunctionCall([NotNull] SinumerikParser.MmodeFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>mmodeFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMmodeFunctionCall([NotNull] SinumerikParser.MmodeFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>feedFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFeedFunctionCall([NotNull] SinumerikParser.FeedFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>feedFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFeedFunctionCall([NotNull] SinumerikParser.FeedFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>speedFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpeedFunctionCall([NotNull] SinumerikParser.SpeedFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>speedFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpeedFunctionCall([NotNull] SinumerikParser.SpeedFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>toolNumberFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterToolNumberFunctionCall([NotNull] SinumerikParser.ToolNumberFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>toolNumberFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitToolNumberFunctionCall([NotNull] SinumerikParser.ToolNumberFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>toolNameFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterToolNameFunctionCall([NotNull] SinumerikParser.ToolNameFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>toolNameFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitToolNameFunctionCall([NotNull] SinumerikParser.ToolNameFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>toolIDFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterToolIDFunctionCall([NotNull] SinumerikParser.ToolIDFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>toolIDFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitToolIDFunctionCall([NotNull] SinumerikParser.ToolIDFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>subprogramFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubprogramFunctionCall([NotNull] SinumerikParser.SubprogramFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>subprogramFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubprogramFunctionCall([NotNull] SinumerikParser.SubprogramFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>msgFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMsgFunctionCall([NotNull] SinumerikParser.MsgFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>msgFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMsgFunctionCall([NotNull] SinumerikParser.MsgFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] SinumerikParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] SinumerikParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.ifStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStat([NotNull] SinumerikParser.IfStatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.ifStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStat([NotNull] SinumerikParser.IfStatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.ifGotostat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfGotostat([NotNull] SinumerikParser.IfGotostatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.ifGotostat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfGotostat([NotNull] SinumerikParser.IfGotostatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.elseStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseStat([NotNull] SinumerikParser.ElseStatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.elseStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseStat([NotNull] SinumerikParser.ElseStatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.functionDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDecl([NotNull] SinumerikParser.FunctionDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.functionDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDecl([NotNull] SinumerikParser.FunctionDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStatement([NotNull] SinumerikParser.ForStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStatement([NotNull] SinumerikParser.ForStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStatement([NotNull] SinumerikParser.WhileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStatement([NotNull] SinumerikParser.WhileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.gotoStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGotoStatement([NotNull] SinumerikParser.GotoStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.gotoStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGotoStatement([NotNull] SinumerikParser.GotoStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] SinumerikParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] SinumerikParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.idList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdList([NotNull] SinumerikParser.IdListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.idList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdList([NotNull] SinumerikParser.IdListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.exprList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprList([NotNull] SinumerikParser.ExprListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.exprList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprList([NotNull] SinumerikParser.ExprListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>boolExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolExpression([NotNull] SinumerikParser.BoolExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>boolExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolExpression([NotNull] SinumerikParser.BoolExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>numberExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberExpression([NotNull] SinumerikParser.NumberExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>numberExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberExpression([NotNull] SinumerikParser.NumberExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>identifierExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifierExpression([NotNull] SinumerikParser.IdentifierExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>identifierExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifierExpression([NotNull] SinumerikParser.IdentifierExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>modExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModExpression([NotNull] SinumerikParser.ModExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>modExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModExpression([NotNull] SinumerikParser.ModExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>notExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNotExpression([NotNull] SinumerikParser.NotExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>notExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNotExpression([NotNull] SinumerikParser.NotExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>divExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDivExpression([NotNull] SinumerikParser.DivExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>divExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDivExpression([NotNull] SinumerikParser.DivExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>orExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrExpression([NotNull] SinumerikParser.OrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>orExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrExpression([NotNull] SinumerikParser.OrExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>unaryMinusExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryMinusExpression([NotNull] SinumerikParser.UnaryMinusExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>unaryMinusExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryMinusExpression([NotNull] SinumerikParser.UnaryMinusExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>powerExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPowerExpression([NotNull] SinumerikParser.PowerExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>powerExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPowerExpression([NotNull] SinumerikParser.PowerExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>eqExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqExpression([NotNull] SinumerikParser.EqExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>eqExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqExpression([NotNull] SinumerikParser.EqExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>andExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpression([NotNull] SinumerikParser.AndExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>andExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpression([NotNull] SinumerikParser.AndExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>stringExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringExpression([NotNull] SinumerikParser.StringExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>stringExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringExpression([NotNull] SinumerikParser.StringExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>expressionExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionExpression([NotNull] SinumerikParser.ExpressionExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>expressionExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionExpression([NotNull] SinumerikParser.ExpressionExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>addExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddExpression([NotNull] SinumerikParser.AddExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>addExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddExpression([NotNull] SinumerikParser.AddExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>compExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompExpression([NotNull] SinumerikParser.CompExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>compExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompExpression([NotNull] SinumerikParser.CompExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>nullExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullExpression([NotNull] SinumerikParser.NullExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>nullExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullExpression([NotNull] SinumerikParser.NullExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>functionCallExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCallExpression([NotNull] SinumerikParser.FunctionCallExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>functionCallExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCallExpression([NotNull] SinumerikParser.FunctionCallExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>multExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultExpression([NotNull] SinumerikParser.MultExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>multExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultExpression([NotNull] SinumerikParser.MultExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>listExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListExpression([NotNull] SinumerikParser.ListExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>listExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListExpression([NotNull] SinumerikParser.ListExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>inputExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInputExpression([NotNull] SinumerikParser.InputExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>inputExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInputExpression([NotNull] SinumerikParser.InputExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.gcodeStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGcodeStatement([NotNull] SinumerikParser.GcodeStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.gcodeStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGcodeStatement([NotNull] SinumerikParser.GcodeStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList([NotNull] SinumerikParser.ListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList([NotNull] SinumerikParser.ListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.varlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarlist([NotNull] SinumerikParser.VarlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.varlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarlist([NotNull] SinumerikParser.VarlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.typeDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDef([NotNull] SinumerikParser.TypeDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.typeDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDef([NotNull] SinumerikParser.TypeDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.indexes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexes([NotNull] SinumerikParser.IndexesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.indexes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexes([NotNull] SinumerikParser.IndexesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.printvar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintvar([NotNull] SinumerikParser.PrintvarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.printvar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintvar([NotNull] SinumerikParser.PrintvarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.metkaStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMetkaStart([NotNull] SinumerikParser.MetkaStartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.metkaStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMetkaStart([NotNull] SinumerikParser.MetkaStartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.metkaDest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMetkaDest([NotNull] SinumerikParser.MetkaDestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.metkaDest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMetkaDest([NotNull] SinumerikParser.MetkaDestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.crlfStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCrlfStatement([NotNull] SinumerikParser.CrlfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.crlfStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCrlfStatement([NotNull] SinumerikParser.CrlfStatementContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
