//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/Petr/IdeaProjects/SimpleParser/src\Sinumerik.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SinumerikParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface ISinumerikVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikParser.parse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParse([NotNull] SinumerikParser.ParseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] SinumerikParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] SinumerikParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] SinumerikParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>identifierFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifierFunctionCall([NotNull] SinumerikParser.IdentifierFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>printlnFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintlnFunctionCall([NotNull] SinumerikParser.PrintlnFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>printFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintFunctionCall([NotNull] SinumerikParser.PrintFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>assertFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssertFunctionCall([NotNull] SinumerikParser.AssertFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sizeFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSizeFunctionCall([NotNull] SinumerikParser.SizeFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sinFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSinFunctionCall([NotNull] SinumerikParser.SinFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>cosFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCosFunctionCall([NotNull] SinumerikParser.CosFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>tanFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTanFunctionCall([NotNull] SinumerikParser.TanFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>asinFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsinFunctionCall([NotNull] SinumerikParser.AsinFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>acosFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAcosFunctionCall([NotNull] SinumerikParser.AcosFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>atanFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtanFunctionCall([NotNull] SinumerikParser.AtanFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>atan2FunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtan2FunctionCall([NotNull] SinumerikParser.Atan2FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sqrtFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSqrtFunctionCall([NotNull] SinumerikParser.SqrtFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>truncFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTruncFunctionCall([NotNull] SinumerikParser.TruncFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>absFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbsFunctionCall([NotNull] SinumerikParser.AbsFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>potFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPotFunctionCall([NotNull] SinumerikParser.PotFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>roundFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoundFunctionCall([NotNull] SinumerikParser.RoundFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>modeacFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModeacFunctionCall([NotNull] SinumerikParser.ModeacFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>modeicFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModeicFunctionCall([NotNull] SinumerikParser.ModeicFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>transFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransFunctionCall([NotNull] SinumerikParser.TransFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>atransFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtransFunctionCall([NotNull] SinumerikParser.AtransFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>rotFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRotFunctionCall([NotNull] SinumerikParser.RotFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>arotFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArotFunctionCall([NotNull] SinumerikParser.ArotFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>scaleFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScaleFunctionCall([NotNull] SinumerikParser.ScaleFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ascaleFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAscaleFunctionCall([NotNull] SinumerikParser.AscaleFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>mirrorFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMirrorFunctionCall([NotNull] SinumerikParser.MirrorFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>amirrorFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAmirrorFunctionCall([NotNull] SinumerikParser.AmirrorFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>oriwksFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOriwksFunctionCall([NotNull] SinumerikParser.OriwksFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>oriaxesFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOriaxesFunctionCall([NotNull] SinumerikParser.OriaxesFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>traoriFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTraoriFunctionCall([NotNull] SinumerikParser.TraoriFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>diamonFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiamonFunctionCall([NotNull] SinumerikParser.DiamonFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>diamofFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiamofFunctionCall([NotNull] SinumerikParser.DiamofFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>diam90FunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiam90FunctionCall([NotNull] SinumerikParser.Diam90FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>xcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXcoordFunctionCall([NotNull] SinumerikParser.XcoordFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ycoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitYcoordFunctionCall([NotNull] SinumerikParser.YcoordFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>zcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitZcoordFunctionCall([NotNull] SinumerikParser.ZcoordFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>acoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAcoordFunctionCall([NotNull] SinumerikParser.AcoordFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>bcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBcoordFunctionCall([NotNull] SinumerikParser.BcoordFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ccoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCcoordFunctionCall([NotNull] SinumerikParser.CcoordFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ucoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUcoordFunctionCall([NotNull] SinumerikParser.UcoordFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVcoordFunctionCall([NotNull] SinumerikParser.VcoordFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>wcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWcoordFunctionCall([NotNull] SinumerikParser.WcoordFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ivectFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIvectFunctionCall([NotNull] SinumerikParser.IvectFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>jvectFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJvectFunctionCall([NotNull] SinumerikParser.JvectFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>kvectFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKvectFunctionCall([NotNull] SinumerikParser.KvectFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>radiusFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRadiusFunctionCall([NotNull] SinumerikParser.RadiusFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>turnFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTurnFunctionCall([NotNull] SinumerikParser.TurnFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>mmodeFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMmodeFunctionCall([NotNull] SinumerikParser.MmodeFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>feedFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFeedFunctionCall([NotNull] SinumerikParser.FeedFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>speedFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpeedFunctionCall([NotNull] SinumerikParser.SpeedFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>toolNumberFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToolNumberFunctionCall([NotNull] SinumerikParser.ToolNumberFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>toolNameFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToolNameFunctionCall([NotNull] SinumerikParser.ToolNameFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>toolIDFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToolIDFunctionCall([NotNull] SinumerikParser.ToolIDFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>subprogramFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubprogramFunctionCall([NotNull] SinumerikParser.SubprogramFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>msgFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMsgFunctionCall([NotNull] SinumerikParser.MsgFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] SinumerikParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikParser.ifStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStat([NotNull] SinumerikParser.IfStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikParser.ifGotostat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfGotostat([NotNull] SinumerikParser.IfGotostatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikParser.elseStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseStat([NotNull] SinumerikParser.ElseStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikParser.functionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDecl([NotNull] SinumerikParser.FunctionDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStatement([NotNull] SinumerikParser.ForStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] SinumerikParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikParser.gotoStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGotoStatement([NotNull] SinumerikParser.GotoStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] SinumerikParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikParser.idList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdList([NotNull] SinumerikParser.IdListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprList([NotNull] SinumerikParser.ExprListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>boolExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolExpression([NotNull] SinumerikParser.BoolExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberExpression([NotNull] SinumerikParser.NumberExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>identifierExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifierExpression([NotNull] SinumerikParser.IdentifierExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>modExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModExpression([NotNull] SinumerikParser.ModExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>notExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotExpression([NotNull] SinumerikParser.NotExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>divExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDivExpression([NotNull] SinumerikParser.DivExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>orExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrExpression([NotNull] SinumerikParser.OrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unaryMinusExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryMinusExpression([NotNull] SinumerikParser.UnaryMinusExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>powerExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPowerExpression([NotNull] SinumerikParser.PowerExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>eqExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqExpression([NotNull] SinumerikParser.EqExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>andExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpression([NotNull] SinumerikParser.AndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stringExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringExpression([NotNull] SinumerikParser.StringExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expressionExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionExpression([NotNull] SinumerikParser.ExpressionExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>addExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddExpression([NotNull] SinumerikParser.AddExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>compExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompExpression([NotNull] SinumerikParser.CompExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nullExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullExpression([NotNull] SinumerikParser.NullExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionCallExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCallExpression([NotNull] SinumerikParser.FunctionCallExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>multExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultExpression([NotNull] SinumerikParser.MultExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>listExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListExpression([NotNull] SinumerikParser.ListExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>inputExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInputExpression([NotNull] SinumerikParser.InputExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikParser.gcodeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGcodeStatement([NotNull] SinumerikParser.GcodeStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList([NotNull] SinumerikParser.ListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikParser.varlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarlist([NotNull] SinumerikParser.VarlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikParser.typeDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeDef([NotNull] SinumerikParser.TypeDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikParser.indexes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexes([NotNull] SinumerikParser.IndexesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikParser.metkaStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMetkaStart([NotNull] SinumerikParser.MetkaStartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikParser.metkaDest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMetkaDest([NotNull] SinumerikParser.MetkaDestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikParser.crlfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCrlfStatement([NotNull] SinumerikParser.CrlfStatementContext context);
}
