//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/Petr/IdeaProjects/SimpleParser/src\Sinumerik.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SinumerikParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface ISinumerikListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.parse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParse([NotNull] SinumerikParser.ParseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.parse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParse([NotNull] SinumerikParser.ParseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] SinumerikParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] SinumerikParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] SinumerikParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] SinumerikParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] SinumerikParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] SinumerikParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.vardefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVardefinition([NotNull] SinumerikParser.VardefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.vardefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVardefinition([NotNull] SinumerikParser.VardefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IdentifierSubprogCall</c>
	/// labeled alternative in <see cref="SinumerikParser.subProgCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifierSubprogCall([NotNull] SinumerikParser.IdentifierSubprogCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IdentifierSubprogCall</c>
	/// labeled alternative in <see cref="SinumerikParser.subProgCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifierSubprogCall([NotNull] SinumerikParser.IdentifierSubprogCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>identifierFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifierFunctionCall([NotNull] SinumerikParser.IdentifierFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>identifierFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifierFunctionCall([NotNull] SinumerikParser.IdentifierFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>printlnFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrintlnFunctionCall([NotNull] SinumerikParser.PrintlnFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>printlnFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrintlnFunctionCall([NotNull] SinumerikParser.PrintlnFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sinFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSinFunctionCall([NotNull] SinumerikParser.SinFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sinFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSinFunctionCall([NotNull] SinumerikParser.SinFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>cosFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCosFunctionCall([NotNull] SinumerikParser.CosFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>cosFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCosFunctionCall([NotNull] SinumerikParser.CosFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>tanFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTanFunctionCall([NotNull] SinumerikParser.TanFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>tanFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTanFunctionCall([NotNull] SinumerikParser.TanFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>asinFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsinFunctionCall([NotNull] SinumerikParser.AsinFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>asinFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsinFunctionCall([NotNull] SinumerikParser.AsinFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>acosFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAcosFunctionCall([NotNull] SinumerikParser.AcosFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>acosFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAcosFunctionCall([NotNull] SinumerikParser.AcosFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>atanFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtanFunctionCall([NotNull] SinumerikParser.AtanFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>atanFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtanFunctionCall([NotNull] SinumerikParser.AtanFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>atan2FunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtan2FunctionCall([NotNull] SinumerikParser.Atan2FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>atan2FunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtan2FunctionCall([NotNull] SinumerikParser.Atan2FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sqrtFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSqrtFunctionCall([NotNull] SinumerikParser.SqrtFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sqrtFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSqrtFunctionCall([NotNull] SinumerikParser.SqrtFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>truncFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTruncFunctionCall([NotNull] SinumerikParser.TruncFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>truncFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTruncFunctionCall([NotNull] SinumerikParser.TruncFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>absFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbsFunctionCall([NotNull] SinumerikParser.AbsFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>absFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbsFunctionCall([NotNull] SinumerikParser.AbsFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>potFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPotFunctionCall([NotNull] SinumerikParser.PotFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>potFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPotFunctionCall([NotNull] SinumerikParser.PotFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>roundFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRoundFunctionCall([NotNull] SinumerikParser.RoundFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>roundFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRoundFunctionCall([NotNull] SinumerikParser.RoundFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>modeacFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModeacFunctionCall([NotNull] SinumerikParser.ModeacFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>modeacFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModeacFunctionCall([NotNull] SinumerikParser.ModeacFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>modeicFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModeicFunctionCall([NotNull] SinumerikParser.ModeicFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>modeicFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModeicFunctionCall([NotNull] SinumerikParser.ModeicFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>xaxisNameFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterXaxisNameFunctionCall([NotNull] SinumerikParser.XaxisNameFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>xaxisNameFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitXaxisNameFunctionCall([NotNull] SinumerikParser.XaxisNameFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>yaxisNameFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterYaxisNameFunctionCall([NotNull] SinumerikParser.YaxisNameFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>yaxisNameFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitYaxisNameFunctionCall([NotNull] SinumerikParser.YaxisNameFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>zaxisNameFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterZaxisNameFunctionCall([NotNull] SinumerikParser.ZaxisNameFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>zaxisNameFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitZaxisNameFunctionCall([NotNull] SinumerikParser.ZaxisNameFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>aaxisNameFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAaxisNameFunctionCall([NotNull] SinumerikParser.AaxisNameFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>aaxisNameFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAaxisNameFunctionCall([NotNull] SinumerikParser.AaxisNameFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>baxisNameFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaxisNameFunctionCall([NotNull] SinumerikParser.BaxisNameFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>baxisNameFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaxisNameFunctionCall([NotNull] SinumerikParser.BaxisNameFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>caxisNameFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaxisNameFunctionCall([NotNull] SinumerikParser.CaxisNameFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>caxisNameFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaxisNameFunctionCall([NotNull] SinumerikParser.CaxisNameFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>transFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTransFunctionCall([NotNull] SinumerikParser.TransFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>transFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTransFunctionCall([NotNull] SinumerikParser.TransFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>atransFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtransFunctionCall([NotNull] SinumerikParser.AtransFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>atransFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtransFunctionCall([NotNull] SinumerikParser.AtransFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>rotFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRotFunctionCall([NotNull] SinumerikParser.RotFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>rotFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRotFunctionCall([NotNull] SinumerikParser.RotFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>arotFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArotFunctionCall([NotNull] SinumerikParser.ArotFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>arotFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArotFunctionCall([NotNull] SinumerikParser.ArotFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>scaleFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScaleFunctionCall([NotNull] SinumerikParser.ScaleFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>scaleFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScaleFunctionCall([NotNull] SinumerikParser.ScaleFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ascaleFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAscaleFunctionCall([NotNull] SinumerikParser.AscaleFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ascaleFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAscaleFunctionCall([NotNull] SinumerikParser.AscaleFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>mirrorFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMirrorFunctionCall([NotNull] SinumerikParser.MirrorFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>mirrorFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMirrorFunctionCall([NotNull] SinumerikParser.MirrorFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>amirrorFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAmirrorFunctionCall([NotNull] SinumerikParser.AmirrorFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>amirrorFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAmirrorFunctionCall([NotNull] SinumerikParser.AmirrorFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>oriwksFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOriwksFunctionCall([NotNull] SinumerikParser.OriwksFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>oriwksFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOriwksFunctionCall([NotNull] SinumerikParser.OriwksFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>oriaxesFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOriaxesFunctionCall([NotNull] SinumerikParser.OriaxesFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>oriaxesFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOriaxesFunctionCall([NotNull] SinumerikParser.OriaxesFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>traoriFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTraoriFunctionCall([NotNull] SinumerikParser.TraoriFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>traoriFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTraoriFunctionCall([NotNull] SinumerikParser.TraoriFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>diamonFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDiamonFunctionCall([NotNull] SinumerikParser.DiamonFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>diamonFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDiamonFunctionCall([NotNull] SinumerikParser.DiamonFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>diamofFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDiamofFunctionCall([NotNull] SinumerikParser.DiamofFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>diamofFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDiamofFunctionCall([NotNull] SinumerikParser.DiamofFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>diam90FunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDiam90FunctionCall([NotNull] SinumerikParser.Diam90FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>diam90FunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDiam90FunctionCall([NotNull] SinumerikParser.Diam90FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>displofFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDisplofFunctionCall([NotNull] SinumerikParser.DisplofFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>displofFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDisplofFunctionCall([NotNull] SinumerikParser.DisplofFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>displonFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDisplonFunctionCall([NotNull] SinumerikParser.DisplonFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>displonFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDisplonFunctionCall([NotNull] SinumerikParser.DisplonFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sblofFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSblofFunctionCall([NotNull] SinumerikParser.SblofFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sblofFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSblofFunctionCall([NotNull] SinumerikParser.SblofFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sblonFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSblonFunctionCall([NotNull] SinumerikParser.SblonFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sblonFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSblonFunctionCall([NotNull] SinumerikParser.SblonFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>saveFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSaveFunctionCall([NotNull] SinumerikParser.SaveFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>saveFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSaveFunctionCall([NotNull] SinumerikParser.SaveFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>xcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterXcoordFunctionCall([NotNull] SinumerikParser.XcoordFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>xcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitXcoordFunctionCall([NotNull] SinumerikParser.XcoordFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ycoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterYcoordFunctionCall([NotNull] SinumerikParser.YcoordFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ycoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitYcoordFunctionCall([NotNull] SinumerikParser.YcoordFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>zcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterZcoordFunctionCall([NotNull] SinumerikParser.ZcoordFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>zcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitZcoordFunctionCall([NotNull] SinumerikParser.ZcoordFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>acoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAcoordFunctionCall([NotNull] SinumerikParser.AcoordFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>acoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAcoordFunctionCall([NotNull] SinumerikParser.AcoordFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>bcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBcoordFunctionCall([NotNull] SinumerikParser.BcoordFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>bcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBcoordFunctionCall([NotNull] SinumerikParser.BcoordFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ccoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCcoordFunctionCall([NotNull] SinumerikParser.CcoordFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ccoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCcoordFunctionCall([NotNull] SinumerikParser.CcoordFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ucoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUcoordFunctionCall([NotNull] SinumerikParser.UcoordFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ucoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUcoordFunctionCall([NotNull] SinumerikParser.UcoordFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVcoordFunctionCall([NotNull] SinumerikParser.VcoordFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVcoordFunctionCall([NotNull] SinumerikParser.VcoordFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>wcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWcoordFunctionCall([NotNull] SinumerikParser.WcoordFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>wcoordFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWcoordFunctionCall([NotNull] SinumerikParser.WcoordFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ivectFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIvectFunctionCall([NotNull] SinumerikParser.IvectFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ivectFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIvectFunctionCall([NotNull] SinumerikParser.IvectFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>jvectFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJvectFunctionCall([NotNull] SinumerikParser.JvectFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>jvectFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJvectFunctionCall([NotNull] SinumerikParser.JvectFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>kvectFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKvectFunctionCall([NotNull] SinumerikParser.KvectFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>kvectFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKvectFunctionCall([NotNull] SinumerikParser.KvectFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>radiusFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRadiusFunctionCall([NotNull] SinumerikParser.RadiusFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>radiusFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRadiusFunctionCall([NotNull] SinumerikParser.RadiusFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>turnFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTurnFunctionCall([NotNull] SinumerikParser.TurnFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>turnFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTurnFunctionCall([NotNull] SinumerikParser.TurnFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>rplFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRplFunctionCall([NotNull] SinumerikParser.RplFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>rplFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRplFunctionCall([NotNull] SinumerikParser.RplFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>mmodeFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMmodeFunctionCall([NotNull] SinumerikParser.MmodeFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>mmodeFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMmodeFunctionCall([NotNull] SinumerikParser.MmodeFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>feedFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFeedFunctionCall([NotNull] SinumerikParser.FeedFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>feedFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFeedFunctionCall([NotNull] SinumerikParser.FeedFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>speedFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpeedFunctionCall([NotNull] SinumerikParser.SpeedFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>speedFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpeedFunctionCall([NotNull] SinumerikParser.SpeedFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>toolNumberFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterToolNumberFunctionCall([NotNull] SinumerikParser.ToolNumberFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>toolNumberFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitToolNumberFunctionCall([NotNull] SinumerikParser.ToolNumberFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>toolNameFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterToolNameFunctionCall([NotNull] SinumerikParser.ToolNameFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>toolNameFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitToolNameFunctionCall([NotNull] SinumerikParser.ToolNameFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>toolIDFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterToolIDFunctionCall([NotNull] SinumerikParser.ToolIDFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>toolIDFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitToolIDFunctionCall([NotNull] SinumerikParser.ToolIDFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>msgFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMsgFunctionCall([NotNull] SinumerikParser.MsgFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>msgFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMsgFunctionCall([NotNull] SinumerikParser.MsgFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>setalFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetalFunctionCall([NotNull] SinumerikParser.SetalFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>setalFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetalFunctionCall([NotNull] SinumerikParser.SetalFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stopreFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStopreFunctionCall([NotNull] SinumerikParser.StopreFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stopreFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStopreFunctionCall([NotNull] SinumerikParser.StopreFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>axisByNameFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAxisByNameFunctionCall([NotNull] SinumerikParser.AxisByNameFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>axisByNameFunctionCall</c>
	/// labeled alternative in <see cref="SinumerikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAxisByNameFunctionCall([NotNull] SinumerikParser.AxisByNameFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] SinumerikParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] SinumerikParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.ifStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStat([NotNull] SinumerikParser.IfStatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.ifStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStat([NotNull] SinumerikParser.IfStatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.ifGotostat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfGotostat([NotNull] SinumerikParser.IfGotostatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.ifGotostat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfGotostat([NotNull] SinumerikParser.IfGotostatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.elseStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseStat([NotNull] SinumerikParser.ElseStatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.elseStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseStat([NotNull] SinumerikParser.ElseStatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.functionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDecl([NotNull] SinumerikParser.FunctionDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.functionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDecl([NotNull] SinumerikParser.FunctionDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStatement([NotNull] SinumerikParser.ForStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStatement([NotNull] SinumerikParser.ForStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatement([NotNull] SinumerikParser.WhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatement([NotNull] SinumerikParser.WhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.mcallStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMcallStatement([NotNull] SinumerikParser.McallStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.mcallStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMcallStatement([NotNull] SinumerikParser.McallStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.gotoStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGotoStatement([NotNull] SinumerikParser.GotoStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.gotoStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGotoStatement([NotNull] SinumerikParser.GotoStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.repeatStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeatStatement([NotNull] SinumerikParser.RepeatStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.repeatStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeatStatement([NotNull] SinumerikParser.RepeatStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.caseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseStatement([NotNull] SinumerikParser.CaseStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.caseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseStatement([NotNull] SinumerikParser.CaseStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] SinumerikParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] SinumerikParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.endprogStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEndprogStatement([NotNull] SinumerikParser.EndprogStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.endprogStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEndprogStatement([NotNull] SinumerikParser.EndprogStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.idList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdList([NotNull] SinumerikParser.IdListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.idList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdList([NotNull] SinumerikParser.IdListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprList([NotNull] SinumerikParser.ExprListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprList([NotNull] SinumerikParser.ExprListContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>boolExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolExpression([NotNull] SinumerikParser.BoolExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>boolExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolExpression([NotNull] SinumerikParser.BoolExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>numberExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumberExpression([NotNull] SinumerikParser.NumberExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>numberExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumberExpression([NotNull] SinumerikParser.NumberExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>identifierExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifierExpression([NotNull] SinumerikParser.IdentifierExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>identifierExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifierExpression([NotNull] SinumerikParser.IdentifierExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>modExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModExpression([NotNull] SinumerikParser.ModExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>modExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModExpression([NotNull] SinumerikParser.ModExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>notExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotExpression([NotNull] SinumerikParser.NotExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>notExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotExpression([NotNull] SinumerikParser.NotExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>divExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDivExpression([NotNull] SinumerikParser.DivExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>divExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDivExpression([NotNull] SinumerikParser.DivExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>orExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrExpression([NotNull] SinumerikParser.OrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>orExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrExpression([NotNull] SinumerikParser.OrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>unaryMinusExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryMinusExpression([NotNull] SinumerikParser.UnaryMinusExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>unaryMinusExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryMinusExpression([NotNull] SinumerikParser.UnaryMinusExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>powerExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPowerExpression([NotNull] SinumerikParser.PowerExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>powerExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPowerExpression([NotNull] SinumerikParser.PowerExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>eqExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqExpression([NotNull] SinumerikParser.EqExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>eqExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqExpression([NotNull] SinumerikParser.EqExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>andExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpression([NotNull] SinumerikParser.AndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>andExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpression([NotNull] SinumerikParser.AndExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stringExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringExpression([NotNull] SinumerikParser.StringExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stringExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringExpression([NotNull] SinumerikParser.StringExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expressionExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionExpression([NotNull] SinumerikParser.ExpressionExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expressionExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionExpression([NotNull] SinumerikParser.ExpressionExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>addExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddExpression([NotNull] SinumerikParser.AddExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>addExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddExpression([NotNull] SinumerikParser.AddExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>compExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompExpression([NotNull] SinumerikParser.CompExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>compExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompExpression([NotNull] SinumerikParser.CompExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>nullExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNullExpression([NotNull] SinumerikParser.NullExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>nullExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNullExpression([NotNull] SinumerikParser.NullExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>functionCallExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCallExpression([NotNull] SinumerikParser.FunctionCallExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>functionCallExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCallExpression([NotNull] SinumerikParser.FunctionCallExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>multExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultExpression([NotNull] SinumerikParser.MultExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>multExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultExpression([NotNull] SinumerikParser.MultExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>listExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListExpression([NotNull] SinumerikParser.ListExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>listExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListExpression([NotNull] SinumerikParser.ListExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>inputExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInputExpression([NotNull] SinumerikParser.InputExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>inputExpression</c>
	/// labeled alternative in <see cref="SinumerikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInputExpression([NotNull] SinumerikParser.InputExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.gcodeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGcodeStatement([NotNull] SinumerikParser.GcodeStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.gcodeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGcodeStatement([NotNull] SinumerikParser.GcodeStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList([NotNull] SinumerikParser.ListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList([NotNull] SinumerikParser.ListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.varlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarlist([NotNull] SinumerikParser.VarlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.varlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarlist([NotNull] SinumerikParser.VarlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.typeDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDef([NotNull] SinumerikParser.TypeDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.typeDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDef([NotNull] SinumerikParser.TypeDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.indexes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexes([NotNull] SinumerikParser.IndexesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.indexes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexes([NotNull] SinumerikParser.IndexesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.printvar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrintvar([NotNull] SinumerikParser.PrintvarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.printvar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrintvar([NotNull] SinumerikParser.PrintvarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.metkaStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMetkaStart([NotNull] SinumerikParser.MetkaStartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.metkaStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMetkaStart([NotNull] SinumerikParser.MetkaStartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.metkaDest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMetkaDest([NotNull] SinumerikParser.MetkaDestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.metkaDest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMetkaDest([NotNull] SinumerikParser.MetkaDestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikParser.crlfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCrlfStatement([NotNull] SinumerikParser.CrlfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikParser.crlfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCrlfStatement([NotNull] SinumerikParser.CrlfStatementContext context);
}
